export const MOVIE_CARD_COUNT = 15;
export const SHOWING_EXTRA_MOVIES_COUNT = 4;
export const SHOWING_MOVIES_COUNT_ON_START = 5;
export const SHOWING_MOVIES_COUNT_BY_BUTTON = 5;
export const DESCRIPTION_LIMIT = 140;
